<?= $this->fetch('common/breadcrumb.phtml', ['breadcrumb' => $breadcrumb]); ?>

<div id="lightgallery">
    <?= $this->fetch('gallery/partial/folder.phtml', ['path' => $path, 'folders' => $folders]); ?>
    <?= $this->fetch('gallery/partial/image.phtml', ['path' => $path, 'files' => $files]); ?>

    <div class="clearfix"></div>
</div>

<div class="text-center mtxl mbxl">
    carokarsten.ddns.net<br><span style="font-size:0.9em">&copy; 2016</span>
</div>
