
<h3 class="text-center">
    <small><span class="glyphicon glyphicon-picture"></span></small><br>carokarsten.ddns.net<br><small>BILDER GALERIE</small>
</h3>

<?= $this->fetch('common/breadcrumb.phtml', ['breadcrumb' => $breadcrumb]); ?>

<div id="lightgallery">
    <?= $this->fetch('gallery/partial/folder.phtml', ['path' => $path, 'folders' => $folders]); ?>
    <?= $this->fetch('gallery/partial/image.phtml', ['path' => $path, 'files' => $files]); ?>

    <div class="clearfix"></div>
</div>

<div class="text-center mtxl mbxl">
    <span style="font-size:0.9em">&copy;<br>2016</span>
</div>
