<h3 class="text-center">
    <small>
        <a href="/"><span class="glyphicon glyphicon-camera"></span></a>
    </small><br>carokarsten.ddns.net<br><small>TIMELINE</small>
</h3>

<div id="lightgallery">
    <?= $this->fetch('gallery/partial/folder/up.phtml', ['up' => ($up == $root ? null : $up)]); ?>
    <?= $this->fetch('gallery/partial/folder/down.phtml', ['path' => $path, 'folders' => $folders]); ?>
    <?= $this->fetch('gallery/partial/image.phtml', ['path' => $path, 'files' => $files]); ?>

    <div class="clearfix"></div>
</div>

<div class="text-center mbxl">
    <span style="font-size:0.9em">&copy;<br>2016</span>
</div>
