<?php foreach ($folders as $idx => $folder) : ?>
    <div class="gallery-item">
        <div class="gallery-folder" title="folder">
            <a href="<?= $folder['path'] ?>"><img src="/storage/<?= $folder['thumbnail'] ?>"/></a>
            <div class="gallery-folder-image-count">
                <?= $folder['files'] ?>
            </div>
            <div class="gallery-folder-description">
                <?= $folder['name'] ?>
            </div>
        </div>
    </div>
<?php endforeach; ?>
