<?php foreach ($files as $file) : ?>
    <div class="gallery-item">
        <div class="gallery-image" title="image">
            <a href="<?= $path ?>/<?= $file["preview"] ?>" data-sub-html="#img-description-<?= $file["idx"] ?>"><img src="<?= $path ?>/<?= $file["thumb"] ?>"/></a>
            <div class="gallery-folder-image-count">
                <?= $file["idx"] ?>
            </div>
            <div class="gallery-image-filename">
                <?= $file["title"] ?>
            </div>
        </div>
        <?= $this->fetch('gallery/partial/description.phtml', ['idx' => $file["idx"], 'description' => $file['description']]); ?>
    </div>
<?php endforeach; ?>


