<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>gallery</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/plugin/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/plugin/bootstrap/css/bootstrap-theme.min.css">

    <link type="text/css" rel="stylesheet" href="/plugin/lightgallery/css/lightgallery.min.css" />

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

    <div id="lightgallery">
        <a href="http://carokarsten.ddns.net/storage/calendar/03.jpg">
            <img src="http://carokarsten.ddns.net/storage/calendar/03.jpg" width="200px"/>
        </a>
        <a href="http://carokarsten.ddns.net/storage/calendar/06.jpg">
            <img src="http://carokarsten.ddns.net/storage/calendar/06.jpg" width="200px"/>
        </a>
    </div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- A jQuery plugin that adds cross-browser mouse wheel support -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/plugin/bootstrap/js/bootstrap.min.js"></script>

<script src="/plugin/lightgallery/js/lightgallery.min.js"></script>

<script type="text/javascript">
    $(document).ready(function() {
        $("#lightgallery").lightGallery();
    });
</script>

</body>
</html>
