<!DOCTYPE html>
<html lang="en">
<head>

    <meta charset="utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <meta http-equiv="cache-control" content="max-age=0" />
    <meta http-equiv="cache-control" content="no-cache" />
    <meta http-equiv="expires" content="0" />
    <meta http-equiv="expires" content="Tue, 01 Jan 1980 1:00:00 GMT" />
    <meta http-equiv="pragma" content="no-cache" />

    <title>...</title>

    <!-- Bootstrap -->
    <link rel="stylesheet" href="/style/extensions/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="/style/extensions/bootstrap/css/bootstrap-theme.min.css">

    <link type="text/css" rel="stylesheet" href="/style/extensions/lightgallery/css/lightgallery.min.css"/>
    <link type="text/css" rel="stylesheet" href="/style/extensions/animate/animate.css">
    <link type="text/css" rel="stylesheet" href="/style/gallery.css?<?= time() ?>">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<body>

<div class="container">
    <?= $content ?>
</div>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>

<!-- A jQuery plugin that adds cross-browser mouse wheel support -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-mousewheel/3.1.13/jquery.mousewheel.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="/style/extensions/bootstrap/js/bootstrap.min.js"></script>

<script src="/style/extensions/lightgallery/js/lightgallery.min.js"></script>
<script src="/style/extensions/lightgallery/js/lg-autoplay.min.js"></script>
<script src="/style/extensions/lightgallery/js/lg-fullscreen.min.js"></script>
<script src="/style/extensions/lightgallery/js/lg-video.min.js"></script>
<script src="/style/extensions/lightgallery/js/lg-zoom.min.js"></script>

<script src="/style/extensions/notify/bootstrap-notify.min.js"></script>

<script type="text/javascript">
    $(document).ready(function () {
        $("#lightgallery").lightGallery({"selector": ".gallery-image > a"});


//        $.notify({
//            message: 'NOTIFICATION'
//        }, {
//            type: 'gallery',
//            placement: {
//                from: "top",
//                align: "right"
//            },
//            allow_dismiss: true,
//            delay: 0,
//            animate: {
//                enter: 'animated fadeInRight',
//                exit: 'animated fadeOutRight'
//            }
//        });
    });
</script>

</body>
</html>
